name: Test GCP Connection
on:
  push:
    branches: [ main ]
jobs:
  test-connection:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout Reposity'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authentication to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/582508909454/locations/global/workloadIdentityPools/wif-pool-github-gcp/providers/github-provider'
          service_account: 'github-wif-test@cms-vpc-control-poc.iam.gserviceaccount.com'
      - name: 'Verify Connection'
        run: |
          gcloud auth list
          gcloud config list
          gcloud storage ls
          echo "Connection is Successful!"
